### ISSUE TITLE
JOSS - Add contributing guide

### ISSUE THREAD

**Issue by glemaitre** [UniNE-CHYN/mmappickle#8]
You should add a contributing guide: how to open issue, submit PR, etc.
You can add the template in the GitHub as well.

**Comment by lfasnacht** [comment]
http://mmappickle.readthedocs.io/en/latest/contributing.html, is that ok for you?

I personally don't think adding github templates for issues is required. Most of the support request I receive for my other projects are usually not that bad, and it seems that a lot of people prefer to write directly to me instead of using github's tracker (and I see no way to avoid that..).
