### ISSUE TITLE
JOSS - Documentation

### ISSUE THREAD

**Issue by glemaitre** [UniNE-CHYN/mmappickle#9]
I really think that you should improve the landing page of the documentation. Provide the visions of the project and the use case in which a user need your package. In this regard I might remove the getting started and add it to the landing page.

You might want to add additional use case examples, in a gallery for instance (you might want to check sphinx-gallery).

**Comment by glemaitre** [comment]
You can then improve the first page of the `paper.md` as well.

**Comment by lfasnacht** [comment]
I'm not totally sure what you mean, I guess you were referring to joblib documentation, but I don't see how to translate it directly to my library, as it doesn't strive to be as general as joblib. Moreover, it's difficult to provide meaningful examples, as usually the data files are very large (otherwise it would not make sense to use mmappickle).

Nevertheless, I've added some information to the landing page, can you give me some feedback about that?

Thanks a lot!

**Comment by glemaitre** [comment]
Your changes are what I had in mind. Regarding the vision,it was basically what you had in the paper and not something related to joblib, so I pretty much like the changes.

My only concern is more related to the name of the package: I really see the benefit of the mmapdict and I find it quite different from mmappickle. For me the real benefit is that you can memmap dynamically and mmappickle does not allow to know that.

**Comment by lfasnacht** [comment]
The thing is that I also have a ``mmaplist`` class, which is a sequence-like object having more or less the same "nice" properties as ``mmapdict``. It is not released yet since I haven't used it in more than a few tests, and I'm not confident enough to add it to the public repository (contrary to ``mmapdict`` which was heavily used during the last year), but I plan to do so...  It would require some refactoring to meet my quality standards. Therefore I'd prefer to keep the name general.

Regarding ``paper.md``, what do you think I would have to change/add?

**Comment by glemaitre** [comment]
> The thing is that I also have a mmaplist class,

I see. That would make sense. I still don't know if containing `pickle` in the package name is the best. But this is your call ;).

> Regarding paper.md, what do you think I would have to change/add?

I might mention joblib and state that basically you have the advantage of making dynamic mmaping. I believed at the beginning that you had some statement regarding performance but it does not seem so.

**Comment by lfasnacht** [comment]
Thank you very much for your suggestion. I tried to follow your advice, there is a new version compiled in the [review issue](https://github.com/openjournals/joss-reviews/issues/651), does that seems better to you?
